# Generated by Django 4.0.3 on 2022-04-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_remove_post_link_business_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
